apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "creative-ad-api.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "creative-ad-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  API_HOST: {{ .Values.config.apiHost | quote }}
  API_PORT: {{ .Values.config.apiPort | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.config.mlflowTrackingUri | quote }}
  MODEL_ARTIFACT_PATH: {{ .Values.config.modelArtifactPath | quote }}
