{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "creative-ad-api.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "creative-ad-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.secret.awsDefaultRegion | quote }}
{{- end }}
